### PR TITLE
Migration to Mkdocs material

### PR DESCRIPTION
**Pull request by eeintech**
@SchrodingersGat I've completed the migration to the Mkdocs material theme. Take a good look and let me know if anything isn't right. For the moment, I did **not** add any more content than what was already present.

I think Github pages should be able to update automatically (or maybe the `mkdocs gh-deploy` command should do it? :thinking: - [reference](https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages)) but I'm not sure.

Oh, and try clicking on any image, you should get a suprise! :stuck_out_tongue:

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I love it! And the zoomy images are great. Thanks for putting so much effort into this :)

**Comment by SchrodingersGat** [comment]
Hmm thought this would be drop-in compatible, having trouble getting mkdocs to build for github...

**Comment by SchrodingersGat** [comment]
Ok, got it worked out. For future reference (mostly for myself:)

`mkdocs gh-deploy --remote-branch master`

**Comment by eeintech** [comment]
Umm this is weird now the content of the site directory is on Github but not the mardown files anymore? 🤔

**Comment by SchrodingersGat** [comment]
Ok, well that's clearly not good. Time to revert and try again.

**Comment by SchrodingersGat** [comment]
Probably should have read this...

image

**Comment by eeintech** [comment]
Mkdocs uses [ghp-import](https://github.com/c-w/ghp-import) tool to build and upload to the `gh-pages` branch, which in turn is used to serve the URL, it looks correct here. The main branch should still be used to keep the projects files though 😃

**Comment by SchrodingersGat** [comment]
The reference page indicates that the `gh-pages` branch does not work for an organization page and you have to use `master`.

However I have what I think is a "cleaner" approach:

https://inventree.readthedocs.io/en/latest/

**Comment by SchrodingersGat** [comment]
I have ported your mkdocs across to the readthedocs page, I think this is "cleaner" than using the github pages

- A simple config file for building the docs every time we push to master
- No user interaction to push using the `gh-deploy` tool

I will remove the inventree.github.io page entirely, and just have inventree.readthedocs.io I think.

The mkdocs approach is a *lot* simpler than the github pages method, now that it's working!

**Comment by SchrodingersGat** [comment]
Oh and the new docs are now over at https://github.com/inventree/inventree-docs

**Comment by eeintech** [comment]
Awesome, glad you found a proper way to do this 😄  Sorry it caused a bit of headache!

**Pull request merged**
